name: Create templates
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
      -
        env:
          CI: true
          SSH_KEY: ${{ secrets.SSH_KEY }}
        run: _template/build.sh
